file = open("trial.txt","w")
file.write("Parang panaginip\n") 
file.write("'Pag ika'y aking kapiling\n") 
file.write("Huwag kang tumingin\n") 
file.write("sa'kin\n") 
file.write("Ako ay nahuhumaling\n") 
file.write("Ako ay nahuhumaling\n") 
file.write("Sa 'yo\n") 
